// src/domains/todo/todo.types.js
export const TodoActionTypes = {
  SET_LISTS: 'SET_LISTS',
  ADD_LIST: 'ADD_LIST',
  SET_ACTIVE_LIST: 'SET_ACTIVE_LIST',
  DELETE_LIST: 'DELETE_LIST',
  UPDATE_LIST: 'UPDATE_LIST',

  SET_ITEMS: 'SET_ITEMS',
  ADD_ITEM: 'ADD_ITEM',
  TOGGLE_ITEM: 'TOGGLE_ITEM', 
  DELETE_ITEM: 'DELETE_ITEM',
  UPDATE_ITEM_TEXT: 'UPDATE_ITEM_TEXT',
};
